#!/bin/sh /etc/rc.common

START=60
STOP=50

USE_PROCD=1

# 初始化数据库, 用于记录接口的流量统计信息
init_database() {
	/usr/sbin/vnstatd --initdb >/dev/null
	logger -t "vnstat" "$FUNCNAME /usr/sbin/vnstatd --initdb >/dev/null"
}

# 初始化interface
init_ifaces() {
	local cfg="$1"
	logger -t "vnstat" "$FUNCNAME cfg:${cfg}"

	init_iface() {
		local ifn="$1"
		/usr/bin/vnstat --add --force -i "$ifn" >/dev/null
		logger -t "vnstat" "$FUNCNAME /usr/bin/vnstat --add --force -i ${ifn} >/dev/null"
	}

	config_list_foreach "$cfg" interface init_iface
}

# 开机时启动服务
start_service() {

	logger -t "vnstat" "$FUNCNAME"

	init_database

	config_load vnstat						# 加载配置文件/etc/config/vnstat
	config_foreach init_ifaces vnstat		# 初始化interface

	procd_open_instance						# 定义一个新的进程实例
	procd_set_param stdout 1				# 设置进程的标准输出（stdout）为 1。这里的 1 代表将输出发送到控制台或日志
	procd_set_param stderr 1				# 设置进程的标准错误输出（stderr）也为 1

	# --nodaemon 不以守护进程模式运行; 
	# --noadd 防止添加新接口。如果网络接口发生变化，vnstatd 不会自动添加新接口的监控;
	# --startempty 指示守护进程启动时不加载已有的数据, 初始化时使用
	# --noremove防止在停止时移除数据库文件
	procd_set_param command /usr/sbin/vnstatd --nodaemon --noadd --startempty --noremove
	procd_set_param file /etc/vnstat.conf	# vnstatd配置文件路径
	procd_set_param respawn					# 进程崩溃或意外退出时自动重启
	procd_close_instance					# 结束定义的进程实例
}

# 重新加载配置文件
reload_service() {
	config_load vnstat
	config_foreach init_ifaces vnstat

	procd_send_signal vnstat				# 通过型号通知守护进程重新加载配置我呢见, 默认发送的是 SIGHUP 或 SIGTERM
}

# 服务触发方式, 当/etc/config/vnstat文件发生变化时,自动重新加载
service_triggers() {
	procd_add_reload_trigger vnstat
}
